"""Users table

Revision ID: 37ae9e0f65ea
Revises: acdaca930efa
Create Date: 2021-05-10 00:23:19.939593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ae9e0f65ea'
down_revision = 'acdaca930efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body2', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body2')
    # ### end Alembic commands ###
