"""add score to posts

Revision ID: 01779ce63493
Revises: 93429bd34278
Create Date: 2021-05-17 01:44:35.965545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01779ce63493'
down_revision = '93429bd34278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'score')
    # ### end Alembic commands ###
